title: MAKE UR WORLD
author: gastonpb
email: gastonpbigi@gmail.com
description: > # 
In this website we will talk about who we can unite the hole world people to make a peaceful world
And to have economic equity over all the corners of this planet. This can help us be quiet and colaborate with the earth recover

# social links
twitter_username:tongatakku
github_username:  gastonpb

show_excerpts: true # set to false to remove excerpts on the homepage
